name: value-scaling
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip:
      - ipykernel
      - matplotlib
      - pandas
      - rliable
      - scikit-learn
      - scipy
      - seaborn
      - tqdm
      - wandb